USE GD2C2023
GO

-------------------Limpiamos tablas---------------------
--Desde adentro para afuera

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'PAGO_VENTA')
DROP TABLE AMCGDD.PAGO_VENTA;

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'VENTA_INMUEBLE')
DROP TABLE AMCGDD.VENTA_INMUEBLE;

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'MEDIO_DE_PAGO')
DROP TABLE AMCGDD.MEDIO_DE_PAGO;

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'MONEDA')
DROP TABLE AMCGDD.MONEDA;

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'ANUNCIO')
DROP TABLE AMCGDD.ANUNCIO;

IF EXISTS (SELECT name FROM sys.tables WHERE name = 'COMPRADOR')
DROP TABLE AMCGDD.COMPRADOR;

---------------------Limpiamos procedimientos---------------------


IF EXISTS (SELECT name FROM sys.procedures WHERE name = 'MIGRACION_MEDIOS_DE_PAGO')
    DROP PROCEDURE AMCGDD.MIGRACION_MEDIOS_DE_PAGO;
GO

IF EXISTS (SELECT name FROM sys.procedures WHERE name = 'MIGRACION_MONEDAS')
    DROP PROCEDURE AMCGDD.MIGRACION_MONEDAS;
GO

IF EXISTS (SELECT name FROM sys.procedures WHERE name = 'MIGRACION_VENTA_INMUEBLES')
    DROP PROCEDURE AMCGDD.MIGRACION_VENTA_INMUEBLES;
GO

IF EXISTS (SELECT name FROM sys.procedures WHERE name = 'MIGRACION_PAGO_VENTA_INMUEBLES')
    DROP PROCEDURE AMCGDD.MIGRACION_PAGO_VENTA_INMUEBLES;
GO



---------------------Limpiamos el esquema---------------------
IF EXISTS (SELECT name FROM sys.schemas WHERE name = 'AMCGDD')
BEGIN
	DROP SCHEMA AMCGDD
END
GO


---------------------Creamos el esquema---------------------

CREATE SCHEMA AMCGDD;
GO

----------------Creamos las tablas sin PK ni FK, pero aclarando cuáles son PK y FK------------------


CREATE TABLE AMCGDD.ANUNCIO (
    ANUNCIO_CODIGO NUMERIC(19,0) PRIMARY KEY
);

------------------------------------COMPRADOR------------------------------------
CREATE TABLE AMCGDD.COMPRADOR (
    COMPRADOR_ID NUMERIC(19,0) PRIMARY KEY
);

------------------------------------MONEDA------------------------------------
CREATE TABLE AMCGDD.MONEDA (
    MONEDA_CODIGO NUMERIC(19,0) IDENTITY(1,1) PRIMARY KEY,
    MONEDA_NOMBRE NVARCHAR(100)
);

------------------------------------MEDIO DE PAGO------------------------------------
CREATE TABLE AMCGDD.MEDIO_DE_PAGO (
    MEDIO_DE_PAGO_ID NUMERIC(19,0) IDENTITY(1,1) PRIMARY KEY,
    MEDIO_DE_PAGO_NOMBRE NVARCHAR(100)
);

------------------------------------VENTA INMUEBLE------------------------------------
CREATE TABLE AMCGDD.VENTA_INMUEBLE (
    VENTA_CODIGO NUMERIC(19,0),
    VENTA_ANUNCIO NUMERIC(19,0),
    VENTA_COMPRADOR NUMERIC(19,0),
    VENTA_FECHA DATETIME,
    VENTA_PRECIO NUMERIC(18,2),
    VENTA_COMISION NUMERIC(18,2),
    VENTA_MONEDA NUMERIC(19,0),
    PRIMARY KEY (VENTA_CODIGO)
    --FOREIGN KEY (VENTA_ANUNCIO) REFERENCES AMCGDD.ANUNCIO(ANUNCIO_CODIGO),
    --FOREIGN KEY (VENTA_COMPRADOR) REFERENCES AMCGDD.COMPRADOR(COMPRADOR_ID),
    --FOREIGN KEY (VENTA_MONEDA) REFERENCES AMCGDD.MONEDA(MONEDA_CODIGO)
);

------------------------------------PAGO VENTA------------------------------------
CREATE TABLE AMCGDD.PAGO_VENTA (
    PAGO_VENTA_CODIGO NUMERIC(19,0) IDENTITY(1,1) PRIMARY KEY,
    PAGO_VENTA_VENTA NUMERIC(19,0),
    PAGO_VENTA_COTIZACION_MONEDA NUMERIC(18,2),
    PAGO_VENTA_MONEDA NUMERIC(19,0),
    PAGO_VENTA_MEDIO_DE_PAGO NUMERIC(19,0),
    PAGO_VENTA_IMPORTE NUMERIC(18,2)
    --FOREIGN KEY (PAGO_VENTA_VENTA) REFERENCES AMCGDD.VENTA_INMUEBLE(VENTA_CODIGO),
    --FOREIGN KEY (PAGO_VENTA_MONEDA) REFERENCES AMCGDD.MONEDA(MONEDA_CODIGO),
    --FOREIGN KEY (PAGO_VENTA_MEDIO_DE_PAGO) REFERENCES AMCGDD.MEDIO_DE_PAGO(MEDIO_DE_PAGO_ID)
);


---------------------VENTA INMUEBLE---------------------
-- ANUNCIO VENTA INMUEBLE
ALTER TABLE AMCGDD.VENTA_INMUEBLE
ADD CONSTRAINT FK_ANUNCIO_VENTA
FOREIGN KEY (VENTA_ANUNCIO) REFERENCES AMCGDD.ANUNCIO;

-- COMPRADOR VENTA INMUEBLE
ALTER TABLE AMCGDD.VENTA_INMUEBLE
ADD CONSTRAINT FK_COMPRADOR_VENTA
FOREIGN KEY (VENTA_COMPRADOR) REFERENCES AMCGDD.COMPRADOR;

-- MONEDA VENTA INMUEBLE
ALTER TABLE AMCGDD.VENTA_INMUEBLE
ADD CONSTRAINT FK_MONEDA_VENTA
FOREIGN KEY (VENTA_MONEDA) REFERENCES AMCGDD.MONEDA;

---------------------PAGO VENTA---------------------
-- VENTA PAGO VENTA
ALTER TABLE AMCGDD.PAGO_VENTA
ADD CONSTRAINT FK_VENTA_PAGO_VENTA
FOREIGN KEY (PAGO_VENTA_VENTA) REFERENCES AMCGDD.VENTA_INMUEBLE;

-- MONEDA PAGO VENTA
ALTER TABLE AMCGDD.PAGO_VENTA
ADD CONSTRAINT FK_MONEDA_PAGO_VENTA
FOREIGN KEY (PAGO_VENTA_MONEDA) REFERENCES AMCGDD.MONEDA;

-- MEDIO DE PAGO PAGO VENTA
ALTER TABLE AMCGDD.PAGO_VENTA
ADD CONSTRAINT FK_MEDIO_PAGO_PAGO_VENTA
FOREIGN KEY (PAGO_VENTA_MEDIO_DE_PAGO) REFERENCES AMCGDD.MEDIO_DE_PAGO;



--/-------------------MIGRACION DE DATOS-------------------/--


GO
----------------------MEDIOS DE PAGO--------------------------
CREATE PROCEDURE AMCGDD.MIGRACION_MEDIOS_DE_PAGO
AS
BEGIN
    PRINT '**MIGRACION** MEDIOS DE PAGO';
    INSERT INTO AMCGDD.MEDIO_DE_PAGO (MEDIO_DE_PAGO_NOMBRE)
    SELECT DISTINCT PAGO_VENTA_MEDIO_PAGO FROM GD_ESQUEMA.MAESTRA
    WHERE PAGO_VENTA_MEDIO_PAGO IS NOT NULL;
END;
GO

---------------------MONEDAS---------------------
CREATE PROCEDURE AMCGDD.MIGRACION_MONEDAS
AS
BEGIN
    PRINT '**MIGRACION** MONEDAS';
    INSERT INTO AMCGDD.MONEDA (MONEDA_NOMBRE)
    SELECT DISTINCT ANUNCIO_MONEDA FROM GD_ESQUEMA.MAESTRA;
END;
GO

/*
INSERT INTO AMCGDD.VENTA_INMUEBLE(VENTA_CODIGO, VENTA_COMISION, VENTA_FECHA, VENTA_MONEDA, VENTA_PRECIO)
SELECT DISTINCT VENTA_CODIGO, VENTA_COMISION, VENTA_FECHA, VENTA_MONEDA, VENTA_PRECIO_VENTA FROM GD_ESQUEMA.MAESTRA
WHERE VENTA_CODIGO IS NOT NULL
*/

CREATE PROCEDURE AMCGDD.MIGRACION_VENTA_INMUEBLES
AS
BEGIN
    PRINT '**MIGRACION** VENTA INMUEBLES';
    INSERT INTO AMCGDD.VENTA_INMUEBLE (VENTA_CODIGO, VENTA_COMISION, VENTA_FECHA, VENTA_MONEDA, VENTA_PRECIO)
    SELECT DISTINCT VENTA_CODIGO, VENTA_COMISION, VENTA_FECHA, MON.MONEDA_CODIGO, VENTA_PRECIO_VENTA
    FROM GD_ESQUEMA.MAESTRA M
    INNER JOIN AMCGDD.MONEDA MON ON M.VENTA_MONEDA = MON.MONEDA_NOMBRE
    WHERE VENTA_CODIGO IS NOT NULL;
END;
GO

CREATE PROCEDURE AMCGDD.MIGRACION_PAGO_VENTA_INMUEBLES
AS
BEGIN
    PRINT '**MIGRACION** PAGO VENTA INMUEBLES';
    INSERT INTO AMCGDD.PAGO_VENTA (PAGO_VENTA_VENTA, PAGO_VENTA_COTIZACION_MONEDA, PAGO_VENTA_IMPORTE,
                                    PAGO_VENTA_MEDIO_DE_PAGO, PAGO_VENTA_MONEDA)
    SELECT VENTA_CODIGO, PAGO_VENTA_COTIZACION, PAGO_VENTA_IMPORTE,
           (SELECT TOP 1 MEDIO_DE_PAGO_ID FROM AMCGDD.MEDIO_DE_PAGO WHERE MEDIO_DE_PAGO_NOMBRE = PAGO_VENTA_MEDIO_PAGO) AS 'MEDIO PAGO',
           (SELECT TOP 1 MONEDA_CODIGO FROM AMCGDD.MONEDA WHERE MONEDA_NOMBRE = PAGO_VENTA_MONEDA) AS 'MONEDA'
    FROM GD_ESQUEMA.MAESTRA
    WHERE VENTA_CODIGO IS NOT NULL;
END;
GO


EXEC AMCGDD.MIGRACION_MEDIOS_DE_PAGO;
EXEC AMCGDD.MIGRACION_MONEDAS;
EXEC AMCGDD.MIGRACION_VENTA_INMUEBLES;
EXEC AMCGDD.MIGRACION_PAGO_VENTA_INMUEBLES;

/*
SELECT * FROM AMCGDD.Anuncio
SELECT * FROM AMCGDD.Comprador
SELECT * FROM AMCGDD.Medio_de_pago
SELECT * FROM AMCGDD.Moneda
SELECT * FROM AMCGDD.Pago_venta
SELECT * FROM AMCGDD.Venta_inmueble
*/
